# Backward-compatible imports for all utilities
from .geom import (
    # Core geometry functions
    inv_quat,
    inv_T,
    normalize,
    rot6d_to_R,
    R_to_rot6d,
    xyz_to_quat,
    quat_to_R,
    quat_to_xyz,
    R_to_quat,
    trans_R_to_T,
    R_to_T,
    trans_to_T,
    trans_quat_to_T,
    transform_quat_by_quat,
    transform_by_quat,
    axis_angle_to_quat,
    transform_by_xyz,
    transform_by_trans_quat,
    inv_transform_by_quat,
    inv_transform_by_trans_quat,
    transform_pos_quat_by_trans_quat,
    transform_by_R,
    transform_by_trans_R,
    transform_by_T,
    inv_transform_by_T,
    scale_to_T,
    z_up_to_R,
    pos_lookat_up_to_T,
    T_to_pos_lookat_up,
    euler_to_quat,
    euler_to_R,
    slerp,
    random_quaternion,
    zero_pos,
    identity_quat,
    tc_zero_pos,
    tc_identity_quat,
    nowhere,
    default_solver_params,
    default_friction,
    default_dofs_kp,
    default_dofs_kv,
)
from .reference_frame import ReferenceFrames, ReferenceFramesInput
from .ref_dict import RefDict
from .helpers import (
    gs_rand_float,
    check_boolean_tensor,
    wrap_normal_function_as_closure,
    wrap_reset_function_as_closure,
)

# Export everything for backward compatibility
__all__ = [
    # Geometry functions
    "inv_quat",
    "inv_T",
    "normalize",
    "rot6d_to_R",
    "R_to_rot6d",
    "xyz_to_quat",
    "quat_to_R",
    "quat_to_xyz",
    "R_to_quat",
    "trans_R_to_T",
    "R_to_T",
    "trans_to_T",
    "trans_quat_to_T",
    "transform_quat_by_quat",
    "transform_by_quat",
    "axis_angle_to_quat",
    "transform_by_xyz",
    "transform_by_trans_quat",
    "inv_transform_by_quat",
    "inv_transform_by_trans_quat",
    "transform_pos_quat_by_trans_quat",
    "transform_by_R",
    "transform_by_trans_R",
    "transform_by_T",
    "inv_transform_by_T",
    "scale_to_T",
    "z_up_to_R",
    "pos_lookat_up_to_T",
    "T_to_pos_lookat_up",
    "euler_to_quat",
    "euler_to_R",
    "slerp",
    "random_quaternion",
    "zero_pos",
    "identity_quat",
    "tc_zero_pos",
    "tc_identity_quat",
    "nowhere",
    "default_solver_params",
    "default_friction",
    "default_dofs_kp",
    "default_dofs_kv",
    # Reference frame
    "ReferenceFrames",
    "ReferenceFramesInput",
    # Data structures
    "RefDict",
    # Helper functions
    "gs_rand_float",
    "check_boolean_tensor",
    "wrap_normal_function_as_closure",
    "wrap_reset_function_as_closure",
]
